Add support for epd12in48b_v2
Caemor/eink-waveshare-rs pull request #174
Opened 2023-10-23 05:54 UTC by vadimcn

Here's a first draft of my driver for [12.48" module](https://github.com/caemor/epd-waveshare/issues/164).  Does this look like something you'd be willing to integrate?

2023-10-30 18:42 UTC, i-like-noodles commented
I have the same device and same ESP32 and this worked for me. But mine is v1 because it did not come with a v2 sticker as the [documentation](https://www.waveshare.com/wiki/12.48inch_e-Paper_Module_(B)#Version_Guide) says. This device has a slightly different startup procedure in the upstream code [as seen here](https://github.com/waveshareteam/12.48inch-e-paper/blob/558effea7955b082d9ebe01ed2432cf0c2fba7b8/esp32/esp32-epd-12in48/src/utility/EPD_12in48b.cpp#L69), though I'm not sure if it makes a difference. The only thing it seems to change is that the v2 startup flashes a lot more compared to v1 on mine.

I did a quick change to this to implement v1 as well, though I don't know if this is how you would want to implement it. See this [diff.patch](https://github.com/caemor/epd-waveshare/files/13208693/diff.patch)

2024-01-15 17:06 UTC, caemor commented on src/epd12in48b_v2/rect.rs
We should move this to a more unspecific module (e.g. helper or directly at the top level below lib.rs), since it's nothing really specific to the epd12in48b_v2

2024-01-15 17:08 UTC, caemor requested changes
Thanks for your work!

I would prefer to have the example in your own, separate repository, which we can link to from this repository.

The rest looks good to me.

2024-01-15 17:10 UTC, caemor commented
> I have the same device and same ESP32 and this worked for me. But mine is v1 because it did not come with a v2 sticker as the [documentation](https://www.waveshare.com/wiki/12.48inch_e-Paper_Module_(B)#Version_Guide) says. This device has a slightly different startup procedure in the upstream code [as seen here](https://github.com/waveshareteam/12.48inch-e-paper/blob/558effea7955b082d9ebe01ed2432cf0c2fba7b8/esp32/esp32-epd-12in48/src/utility/EPD_12in48b.cpp#L69), though I'm not sure if it makes a difference. The only thing it seems to change is that the v2 startup flashes a lot more compared to v1 on mine.
> 
> I did a quick change to this to implement v1 as well, though I don't know if this is how you would want to implement it. See this [diff.patch](https://github.com/caemor/epd-waveshare/files/13208693/diff.patch)

It would be great to support v1 as well. I think we could solve this with feature-gating without much code duplication.

2024-10-29 15:48 UTC, caemor commented on src/rect.rs
> +//! Rectangle operations
```suggestion
//! Rectangle operations for bigger displays with multiple _windows_
```

2024-10-29 15:51 UTC, caemor commented on src/epd12in48b_v2/mod.rs
> +/// ```
```suggestion
/// ```md
```

2024-10-30 09:55 UTC, caemor approved these changes

2024-10-30 09:55 UTC, merged

2025-09-11 19:48 UTC, ldicarlo commented
Hello, I don't want to open an issue for that since you advised @vadimcn to do it in his repository, but, @vadimcn would you mind, please, show me an example of how to use the driver you wrote here? 
I am not sure that it should be called like other drivers here, since it has 4 screens. 
Thank you for your work, both @caemor  and @vadimcn !

2025-09-11 21:04 UTC, vadimcn commented
Here's my test driver app: https://github.com/vadimcn/epd-waveshare/tree/main/esp32/src

2025-09-12 11:20 UTC, ldicarlo commented
thank you for you prompt answer. I still have a question if you don't mind. 
Would you think that your driver would work also with a raspberry ? I see that I need to instanciate Spi and Pins differently than esp's but I am not sure the code could work. 
I'll adapt your example as I can

2025-09-12 15:26 UTC, vadimcn commented
> Would you think that your driver would work also with a raspberry?

Haven't tried it, but I don't see why not.  That's the whole point of embedded-hal.